# Travis CI

language: ruby
before_script:
  - chmod a+x script/cibuild
script: script/cibuild
sudo: false

rvm:
  - 2.2
  - 2.1
  - 2.0
env:
  - ""
  - BUNTO_VERSION=3.0.0
  - BUNTO_VERSION=1.0.0
matrix:
  include:
    - # GitHub Pages
      rvm: 2.1.1
      env: GH_PAGES=true
